# Generated by Django 3.2.6 on 2021-08-31 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Companies",
            new_name="Company",
        ),
    ]
